don72-s/Project_HS

- Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
- Assets/WorkSpace/KMT/Transfortation/Prefabs/Cap.prefab
- Assets/WorkSpace/KMT/Transfortation/Prefabs/Cube.prefab
- Assets/WorkSpace/KMT/Transfortation/Prefabs/Cyl.prefab
- Assets/WorkSpace/KMT/Transfortation/Prefabs/Pizza.prefab
- Assets/WorkSpace/KMT/Transfortation/Prefabs/Pole.prefab
- Assets/WorkSpace/KMT/Transfortation/Prefabs/Sphere.prefab
- Assets/WorkSpace/KMT/Transfortation/Scripts/FormChanger.cs
- Assets/WorkSpace/LSY/Resources/Runner.prefab
- Assets/WorkSpace/LSY/Scripts/RunnerController.cs
- Assets/WorkSpace/LSY/lsy_GameScene.unity
> [feat] : conbine transformation feat

- Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
- Assets/WorkSpace/KMT/VoiceChat/Audio/AudioMixer.mixer
- Assets/WorkSpace/KMT/VoiceChat/Prefabs/NetworkPrefabs/Resources/CharacterSpeaker.prefab
> [test] : audio test

- Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
- Assets/ProjectHS/Scenes/TestScene.meta
- Assets/ProjectHS/Scenes/TestScene/GameScene_Test.unity
- Assets/ProjectHS/Scenes/TestScene/GameScene_Test.unity.meta
- Assets/ProjectHS/Scenes/TestScene/Resources.meta
- Assets/ProjectHS/Scenes/TestScene/Resources/Player.prefab
- Assets/ProjectHS/Scenes/TestScene/Resources/Player.prefab.meta
- Assets/ProjectHS/Scenes/TestScene/Resources/Runner.prefab
- Assets/ProjectHS/Scenes/TestScene/Resources/Runner.prefab.meta
- Assets/WorkSpace/LSY/Resources/Player.prefab
- Assets/WorkSpace/LSY/Resources/Runner.prefab
- Assets/WorkSpace/LSY/Scripts/RunnerController.cs
- Assets/WorkSpace/PTG/Scripts/GameManager.cs
게임시작/종료, 플레이어 변신/ 플레이어간 상호작용 기능 병합입니다.
> [combine] : 1차 스테이지 기능 병합

- Assets/WorkSpace/KMT/Transfortation/Prefabs/ChangeUICanvas.prefab
- Assets/WorkSpace/KMT/Transfortation/Scripts/ChangeUIBinder.cs
- Assets/WorkSpace/KMT/Transfortation/Scripts/StageData.cs
- Assets/WorkSpace/KMT/VoiceChat/Audio/AudioMixer.mixer
- Assets/WorkSpace/KMT/VoiceChat/Prefabs/NetworkPrefabs/Resources/CharacterSpeaker.prefab
- Assets/WorkSpace/KMT/VoiceChat/Prefabs/NetworkPrefabs/Resources/NewBehaviourScript.cs
- Assets/WorkSpace/KMT/VoiceChat/Prefabs/NetworkPrefabs/Resources/Player_kmt_Voice.prefab
- Assets/WorkSpace/KMT/VoiceChat/Prefabs/VolumeSliderPrefab.prefab
- Assets/WorkSpace/KMT/VoiceChat/Prefabs/VolumeSliderPrefab.prefab.meta
- Assets/WorkSpace/KMT/VoiceChat/Scenes/GameScene_kmt_Voice.unity
- Assets/WorkSpace/KMT/VoiceChat/Scripts/VoiceSliderRegister.cs
- Assets/WorkSpace/KMT/VoiceChat/Scripts/VoiceSliderRegister.cs.meta
- Assets/WorkSpace/KMT/VoiceChat/Scripts/VoiceVolumePanel.cs
- Assets/WorkSpace/KMT/VoiceChat/Scripts/VoiceVolumePanel.cs.meta
- Assets/WorkSpace/KMT/VoiceChat/Scripts/VolumeSlider.cs
- Assets/WorkSpace/KMT/VoiceChat/Scripts/VolumeSlider.cs.meta
- ProjectSettings/EditorSettings.asset
> [feat] : voice volume setting panel

- Assets/ProjectHS/Scenes/TestScene/GameScene_Test.unity
- Assets/WorkSpace/KMT/Transfortation/Prefabs/ChangeUICanvas.prefab
- Assets/WorkSpace/LSY/Resources/Player.prefab
- Assets/WorkSpace/PTG/Scripts/GameManager.cs
> [combine] : combine test 2

- Assets/WorkSpace/kYH/Scripts/LobbySceneCallbacks.cs
- Assets/WorkSpace/kYH/Test_RoomScene.unity
- Assets/WorkSpace/kYH/Test_RoomScene.unity.meta
- ProjectSettings/EditorBuildSettings.asset
방 씬으로 씬 변경 테스트 완료했습니다.
추후 플레이어 스폰이 구현되면 기존의 룸 패널 소스코드를 이식하면 될 것 같습니다.
> 방 씬으로 씬 변경 테스트 완료

- Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
- Assets/WorkSpace/KMT/RoomPlayerSpawn/Scripts/PlayerControllerParent.cs
- Assets/WorkSpace/KMT/RoomPlayerSpawn/Scripts/PlayerControllerParent.cs.meta
- Assets/WorkSpace/KMT/RoomPlayerSpawn/Scripts/RoomPlayerController.cs
- Assets/WorkSpace/LSY/Scripts/PlayerController.cs
- Assets/WorkSpace/LSY/Scripts/RunnerController.cs
플레이어로 취급되는 오브젝트들의 일괄 활성/비활성화 기능 추가
> [feat] : player activation

- Assets/WorkSpace/kYH/Scripts/BackendManager.cs
- Assets/WorkSpace/kYH/Scripts/DataManager.cs
- Assets/WorkSpace/kYH/Scripts/DataManager.cs.meta
> [Feat] 데이터베이스 구조 설계

- Assets/WorkSpace/kYH/KYH_LobbyScene.unity
- Assets/WorkSpace/kYH/Scripts/DataManager.cs
- Assets/WorkSpace/kYH/Scripts/LobbySceneCallbacks.cs
- Assets/WorkSpace/kYH/Scripts/LobbySceneManager.cs
> [Feat] 데이터베이스 쓰기/읽기 연동

- Assets/WorkSpace/kYH/KYH_LobbyScene.unity
- Assets/WorkSpace/kYH/Scripts/DataManager.cs
- Assets/WorkSpace/kYH/Scripts/LobbySceneManager.cs
> [Fix] 중복 로그인 오류 수정

- Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
- Assets/WorkSpace/KMT/Transfortation/Scripts/FormChanger.cs
- Assets/WorkSpace/KMT/Transfortation/Scripts/StageData.cs
- Assets/WorkSpace/KMT/VoiceChat/Scripts/VoiceManager.cs
- Assets/WorkSpace/LSY/Resources/Runner.prefab
> [feat] : runner dead logic

- Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
- Assets/WorkSpace/KMT/MultipleLogin.meta
- Assets/WorkSpace/KMT/MultipleLogin/Resources.meta
- Assets/WorkSpace/KMT/MultipleLogin/Resources/Singletons.meta
- Assets/WorkSpace/KMT/MultipleLogin/Resources/Singletons/DataManager.prefab
- Assets/WorkSpace/KMT/MultipleLogin/Resources/Singletons/DataManager.prefab.meta
- Assets/WorkSpace/KMT/MultipleLogin/Scripts.meta
- Assets/WorkSpace/KMT/MultipleLogin/Scripts/FriendCheck.cs
- Assets/WorkSpace/KMT/MultipleLogin/Scripts/FriendCheck.cs.meta
- Assets/WorkSpace/KMT/MultipleLogin/Scripts/SingletonSetter.cs
- Assets/WorkSpace/KMT/MultipleLogin/Scripts/SingletonSetter.cs.meta
- Assets/WorkSpace/KMT/SeekerBind.meta
- Assets/WorkSpace/KMT/SeekerBind/Scenes.meta
- Assets/WorkSpace/KMT/SeekerBind/Scenes/GameScene_Seeker_Blind.unity
- Assets/WorkSpace/KMT/SeekerBind/Scenes/GameScene_Seeker_Blind.unity.meta
- Assets/WorkSpace/KMT/VoiceChat/Prefabs/NetworkPrefabs/Resources/CharacterSpeaker.prefab
- Assets/WorkSpace/LSY/Resources/Player.prefab
- Assets/WorkSpace/LSY/Resources/Runner.prefab
- Assets/WorkSpace/LSY/Scripts/PlayerController.cs
- Assets/WorkSpace/LSY/lsy_GameScene_Clone.unity.meta
- Assets/WorkSpace/PTG/Scripts/GameManager.cs
- Assets/WorkSpace/kYH/Scenes/KYH_LobbyScene.unity
- Assets/WorkSpace/kYH/Scripts/DataManager.cs
- Assets/WorkSpace/kYH/Scripts/LobbySceneCallbacks.cs
- ProjectSettings/EditorBuildSettings.asset
- ProjectSettings/ProjectSettings.asset
> Combine seeker bind + multiple login

- Assets/WorkSpace/kYH/Scripts/LobbySceneCallbacks.cs
- Assets/WorkSpace/kYH/Scripts/PlayerEntry.cs
- Assets/WorkSpace/kYH/Scripts/RoomUpdate.cs
레디 상태가 비활성화/활성화 되는 오류 수정 1차 병합입니다.
> [Fix] 레디 버튼 오류 수정 과정 1차 병합

- Assets/WorkSpace/KMT/SeekerBind/Scenes/GameScene_Seeker_Blind.unity
- Assets/WorkSpace/kYH/Scenes/GameScene_Test_KYH.unity
- Assets/WorkSpace/kYH/Scripts/CustomProperties.cs
- Assets/WorkSpace/kYH/Scripts/PlayerEntry.cs
- Assets/WorkSpace/kYH/Scripts/RoomCallbacks.cs
- Assets/WorkSpace/kYH/Scripts/RoomManager.cs
레디 상태가 true일 때 로비로 돌아가기 버튼을 비활성화 할 수 있도록 기능을 추가했습니다.
> [Feat] 레디 상태에 따른 로비로 돌아가기 버튼 활성화/비활성화 기능 추가

- Assets/Photon/PhotonUnityNetworking/Resources/PhotonServerSettings.asset
- Assets/WorkSpace/PTG/Scripts/GameManager.cs
맵 로딩중에 마스터 클라이언트가 나갔을 때에 게임 시작 취소처리
> [fix] : exit master client in map loading

- Assets/WorkSpace/KMT/MultipleLogin/Resources/Singletons/DataManager.prefab
- Assets/WorkSpace/KMT/RoomProperty.meta
- Assets/WorkSpace/KMT/RoomProperty/Scripts.meta
- Assets/WorkSpace/KMT/RoomProperty/Scripts/RoomCallback.cs
- Assets/WorkSpace/KMT/RoomProperty/Scripts/RoomCallback.cs.meta
- Assets/WorkSpace/KMT/RoomProperty/Scripts/StageDisplayer.cs
- Assets/WorkSpace/KMT/RoomProperty/Scripts/StageDisplayer.cs.meta
- Assets/WorkSpace/KMT/SeekerBind/Scenes/GameScene_Seeker_Blind.unity
- Assets/WorkSpace/KMT/Transfortation/Datas/ChangeableObjs_stage2.asset
- Assets/WorkSpace/KMT/Transfortation/Datas/ChangeableObjs_stage2.asset.meta
- Assets/WorkSpace/KMT/Transfortation/Scripts/FormChanger.cs
- Assets/WorkSpace/KMT/Transfortation/Scripts/ObjectSlotMachine.cs
- Assets/WorkSpace/KMT/Transfortation/Scripts/SO/ChangeableObjsSO.cs
- Assets/WorkSpace/KMT/Transfortation/Scripts/StageData.cs
- Assets/WorkSpace/kYH/Scripts/CustomProperties.cs
- Assets/WorkSpace/kYH/Scripts/LobbySceneCallbacks.cs
- Assets/WorkSpace/kYH/Scripts/LobbySceneManager.cs
- Assets/WorkSpace/kYH/Scripts/RoomUpdate.cs
방에서 스테이지를 전환하고, 스테이지별로 변신 가능 오브젝트들을 다르게 설정할 수 있는 기능 추가
> Kmt map management

- Assets/WorkSpace/kYH/Scenes/KYH_LobbyScene.unity
> [Add] 로그인 화면 UI 디자인 추가

- Assets/WorkSpace/KMT/Read_Exit_Area.meta
- Assets/WorkSpace/KMT/Read_Exit_Area/Materials.meta
- Assets/WorkSpace/KMT/Read_Exit_Area/Materials/ExitArea.mat
- Assets/WorkSpace/KMT/Read_Exit_Area/Materials/ExitArea.mat.meta
- Assets/WorkSpace/KMT/Read_Exit_Area/Materials/ReadyArea.mat
- Assets/WorkSpace/KMT/Read_Exit_Area/Materials/ReadyArea.mat.meta
- Assets/WorkSpace/KMT/Read_Exit_Area/Scenes.meta
- Assets/WorkSpace/KMT/Read_Exit_Area/Scenes/GameScene_ReadyExit.unity
- Assets/WorkSpace/KMT/Read_Exit_Area/Scenes/GameScene_ReadyExit.unity.meta
- Assets/WorkSpace/KMT/Read_Exit_Area/Scripts.meta
- Assets/WorkSpace/KMT/Read_Exit_Area/Scripts/AreaTrigger.cs
- Assets/WorkSpace/KMT/Read_Exit_Area/Scripts/AreaTrigger.cs.meta
- Assets/WorkSpace/KMT/Read_Exit_Area/Scripts/ExitArea.cs
- Assets/WorkSpace/KMT/Read_Exit_Area/Scripts/ExitArea.cs.meta
- Assets/WorkSpace/KMT/Read_Exit_Area/Scripts/ReadyArea.cs
- Assets/WorkSpace/KMT/Read_Exit_Area/Scripts/ReadyArea.cs.meta
- Assets/WorkSpace/kYH/Scripts/LobbySceneCallbacks.cs
- Assets/WorkSpace/kYH/Scripts/RoomUpdate.cs
- ProjectSettings/EditorBuildSettings.asset
> [feat] : area ready and exit area

- Assets/WorkSpace/kYH/Scenes/KYH_GameScene_Seeker_Blind.unity
- Assets/WorkSpace/kYH/Scripts/RoomManager.cs
> [Add] 방에 튜토리얼 UI 오브젝트 추가

- Assets/WorkSpace/kYH/Prefabs/PlayerEntry.prefab
- Assets/WorkSpace/kYH/Prefabs/PlayerEntry.prefab.meta
- Assets/WorkSpace/kYH/Prefabs/RoomEntry.prefab
- Assets/WorkSpace/kYH/Scenes/KYH_GameScene_Seeker_Blind.unity
- Assets/WorkSpace/kYH/Scripts/PlayerEntry.cs
- Assets/WorkSpace/kYH/Scripts/RoomCallbacks.cs
- Assets/WorkSpace/kYH/Scripts/RoomManager.cs
- Assets/WorkSpace/kYH/Scripts/RoomUpdate.cs
> [Add] 플레이어 목록 UI, Seeker 튜토리얼 UI 추가

- Assets/ProjectHS/Scenes/TestScene/GameScene_Seeker_Blind.unity
- Assets/WorkSpace/KMT/RoomPlayerSpawn/Scripts/RoomPlayerController.cs
- Assets/WorkSpace/KMT/Transfortation/Datas/ChangeableObjs_stage1.asset
- Assets/WorkSpace/KMT/Transfortation/Datas/ChangeableObjs_stage1.asset.meta
- Assets/WorkSpace/KMT/Transfortation/Datas/ChangeableObjs_stage2.asset
- Assets/WorkSpace/KMT/Transfortation/Datas/ChangeableObjs_stage2.asset.meta
- Assets/WorkSpace/KMT/Transfortation/Prefabs/ChangeUICanvas.prefab
- Assets/WorkSpace/KMT/Transfortation/Scripts/FormChanger.cs
- Assets/WorkSpace/KMT/Transfortation/Scripts/ObjectSlotMachine.cs
- Assets/WorkSpace/KMT/Transfortation/Scripts/SO/ChangeableObjsSO.cs
슬롯머신 UI 변신 항목 텍스트가 아니라 이미지로 나오도록 기능 구현
> [feat] : Kmt slot UI

- Assets/ProjectHS/Scenes/TestScene/GameScene_Seeker_Blind.unity
- Assets/WorkSpace/KMT/RoomPlayerSpawn/Scripts/RoomPlayerController.cs
- Assets/WorkSpace/kYH/Scripts/RoomCallbacks.cs
- Assets/WorkSpace/kYH/Scripts/RoomManager.cs
- Assets/WorkSpace/kYH/Scripts/RoomUpdate.cs
> [Chore] Combine UI

- Assets/ProjectHS/Scenes/TestScene/GameScene_Seeker_Blind.unity
- Assets/WorkSpace/KMT/MultipleLogin/Resources/Singletons/DataManager.prefab
- Assets/WorkSpace/KMT/OptionParam.meta
- Assets/WorkSpace/KMT/OptionParam/Scripts.meta
- Assets/WorkSpace/KMT/OptionParam/Scripts/OptionDataParams.cs
- Assets/WorkSpace/KMT/OptionParam/Scripts/OptionDataParams.cs.meta
- Assets/WorkSpace/KMT/OptionParam/Scripts/OptionPanel.cs
- Assets/WorkSpace/KMT/OptionParam/Scripts/OptionPanel.cs.meta
- Assets/WorkSpace/KMT/OptionParam/Scripts/SFXRegister.cs
- Assets/WorkSpace/KMT/OptionParam/Scripts/SFXRegister.cs.meta
- Assets/WorkSpace/KMT/RoomPlayerSpawn/Scripts/RoomPlayerController.cs
- Assets/WorkSpace/LSY/Resources/Player.prefab
- Assets/WorkSpace/LSY/Scripts/AudioManager.cs
- Assets/WorkSpace/LSY/Scripts/PlayerController.cs
- Assets/WorkSpace/LSY/Scripts/RunnerController.cs
- Assets/WorkSpace/kYH/Scripts/DataManager.cs
> [feat] : connect optionparams

- Assets/WorkSpace/KMT/Transfortation/Prefabs/ChangeUICanvas.prefab
- Assets/WorkSpace/kYH/Prefabs/EmailPopup.prefab
- Assets/WorkSpace/kYH/Prefabs/EmailPopup.prefab.meta
- Assets/WorkSpace/kYH/Prefabs/PlayerEntry.prefab
- Assets/WorkSpace/kYH/Prefabs/RoomEntry.prefab
- Assets/WorkSpace/kYH/Scenes/KYH_LobbyScene.unity
- Assets/WorkSpace/kYH/Scripts/LobbySceneManager.cs
- UI의 디자인, 위치를 일부 수정했습니다.
- 로비 UI의 폰트를 수정했습니다.
> [Chore] UI 수정

- Assets/ProjectHS/Scenes/LobbyScene/ObjHider.cs
> [feat] : objhide randomly

- Assets/ProjectHS/Scenes/GameScene/GameScene_Seeker_Blind.unity
- Assets/WorkSpace/KMT/VoiceChat/Prefabs/VoiceContorlPanelCanvas.prefab
- Assets/WorkSpace/KMT/VoiceChat/Prefabs/VolumeSliderPrefab.prefab
- Assets/WorkSpace/kYH/Prefabs/PlayerEntry.prefab
보이스챗/설정 팝업창과 튜토리얼의 UI를 한글 폰트를 적용하여 수정했습니다.
> [Chore] 보이스챗/설정 팝업창, 튜토리얼 UI 수정
